# Generated by Django 2.2.5 on 2020-06-28 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collegemajor',
            fields=[
                ('instnm', models.TextField(blank=True, null=True)),
                ('control', models.TextField(blank=True, null=True)),
                ('main', models.TextField(blank=True, null=True)),
                ('cipcode', models.TextField(blank=True, null=True)),
                ('cipdesc', models.TextField(blank=True, null=True)),
                ('credlev', models.TextField(blank=True, null=True)),
                ('creddesc', models.TextField(blank=True, null=True)),
                ('count', models.TextField(blank=True, null=True)),
                ('debtmedian', models.TextField(blank=True, null=True)),
                ('debtpayment10yr', models.TextField(blank=True, null=True)),
                ('debtmean', models.TextField(blank=True, null=True)),
                ('titleivcount', models.TextField(blank=True, null=True)),
                ('earningscount', models.TextField(blank=True, null=True)),
                ('md_earn_wne', models.TextField(blank=True, null=True)),
                ('ipedscount1', models.TextField(blank=True, null=True)),
                ('ipedscount2', models.TextField(blank=True, null=True)),
                ('id', models.TextField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'collegemajor',
                'managed': False,
            },
        ),
    ]
